name: viewer_tracker
description: "Projeto flutter para visualizar modelos 3D"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.7.0
  file_picker: ^8.0.0
  google_mlkit_pose_detection: ^0.14.0
  google_mlkit_commons: ^0.11.0
  path_provider: ^2.1.1
  ffmpeg_kit_flutter_new: ^4.1.0
  vector_math: ^2.1.4
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo.png
  android_gravity: center
  android_12:
    image: assets/logo.png
    color: "#FFFFFF"
  fullscreen: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon_launcher.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/Character_output.glb
    - assets/index.html
    - assets/icon_v2.png